#!/usr/bin/env bash
#pings an IP address passed as an argument.
#Accepts a string as an argument
#Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument
#Ping the IP 5 times

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
