#!/usr/bin/env bash
#stopped our 4-to_infinity_and_beyond process using ctrl+c
#You must use kill (SIGkill)

#git pid of process first
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminate infinite process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
