#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# if 4th "bad Luck",  8th "good Luck" else "Best School"

count=0

while [ $count -lt 10 ]
do
        if [ $count -eq 4 ]
        then
                echo "bad luck"
	elif [ $count -eq 8 ]
        then
                echo "good luck"
	else
	        echo "Best School"
	fi
        (( count++ ))
done
