#!/usr/bin/env bash
# should check if the file exists

if [ -e "School" ]
then
	echo "school file exists"
	if [ -s "School" ]
	then
		echo "School file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "School" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
